services:
  - type: redis
    name: production-redis-testnet-alertexer
    ipAllowList: [] # no external connection allowed
    region: frankfurt
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: allkeys-lru # optional (defaults to allkeys-lru)

  - type: redis
    name: production-redis-mainnet-alertexer
    ipAllowList: [] # no external connection allowed
    region: frankfurt
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: allkeys-lru # optional (defaults to allkeys-lru)

  - type: worker
    name: production-alertexer-testnet
    region: frankfurt
    env: docker
    repo: https://github.com/near/alertexer.git
    branch: production
    dockerCommand: ./alertexer testnet from-interruption
    numInstances: 1
    plan: starter
    envVars:
      - key: REDIS_CONNECTION_STRING
        fromService:
          type: redis
          name: production-redis-testnet-alertexer
          property: connectionString

  - type: worker
    name: production-alertexer-mainnet
    region: frankfurt
    env: docker
    repo: https://github.com/near/alertexer.git
    branch: production
    dockerCommand: ./alertexer mainnet from-interruption
    numInstances: 1
    plan: starter
    envVars:
      - key: REDIS_CONNECTION_STRING
        fromService:
          type: redis
          name: production-redis-mainnet-alertexer
          property: connectionString

